// ============================================================
// Proyecto Centurion – Core Domain Types
// Stellar Fintech Platform
// ============================================================

// ---------------------------------------------------------------------------
// Primitive type aliases
// ---------------------------------------------------------------------------

/** All asset codes supported by the platform. */
export type AssetCode = 'MXN' | 'USD' | 'GOLD' | 'XLM'

/** Stellar network environment. */
export type NetworkType = 'testnet' | 'mainnet'

/** Lifecycle states of a cross-border payment. */
export type PaymentStatus = 'PENDING' | 'SUBMITTED' | 'SETTLED' | 'FAILED'

/** Lifecycle states of a QR checkout session. */
export type SessionStatus = 'PENDING' | 'SCANNED' | 'SETTLED' | 'EXPIRED'

// ---------------------------------------------------------------------------
// Asset configuration
// ---------------------------------------------------------------------------

/**
 * Describes a custom Stellar asset issued and managed by Centurion.
 * Immutable once deployed; lives in the backend config layer.
 */
export interface CenturionAsset {
  /** Three-to-twelve-character Stellar asset code. */
  code: AssetCode

  /** G… public key of the issuing account. */
  issuerPublic: string

  /** G… public key of the distribution account (holds circulating supply). */
  distributorPublic: string

  /**
   * Maximum units that will ever be issued, represented as a decimal string
   * (e.g. "10000000.0000000") to avoid floating-point precision loss.
   */
  maxSupply: string

  /** Semantic purpose used by business logic. */
  purpose: 'payment' | 'investment'
}

// ---------------------------------------------------------------------------
// Payment record
// ---------------------------------------------------------------------------

/**
 * Persisted record of a single path-payment execution.
 * One PaymentRecord maps 1-to-1 with a Stellar transaction once settled.
 */
export interface PaymentRecord {
  /** UUID v4, primary key in the payments table. */
  id: string

  /** Current lifecycle state. */
  status: PaymentStatus

  /** Asset the sender debits from their wallet. */
  sendAsset: AssetCode

  /** Asset the merchant receives (always MXN in the current design). */
  destAsset: AssetCode

  /**
   * Maximum amount the sender will spend, decimal string.
   * Computed from Horizon strict-receive path-find + slippage buffer.
   */
  sendAmount: string

  /**
   * Exact amount the merchant will receive, decimal string.
   * Set at quote time and locked.
   */
  destAmount: string

  /** G… public key of the sender's Stellar account. */
  senderAddr: string

  /** G… public key of the merchant's Stellar account. */
  merchantAddr: string

  /**
   * Stellar transaction hash (64-char hex) once the transaction has been
   * submitted to the network.  Undefined while status is PENDING.
   */
  stellarTxHash?: string

  /**
   * Ordered list of intermediate asset codes used in the Stellar path.
   * Empty array means a direct payment (no hops).
   * Example: ['XLM'] means USD → XLM → MXN.
   */
  pathUsed: AssetCode[]

  /** UTC timestamp when the backend created this record. */
  createdAt: Date

  /** UTC timestamp when the Stellar ledger settled the payment. */
  settledAt?: Date
}

// ---------------------------------------------------------------------------
// QR checkout session
// ---------------------------------------------------------------------------

/**
 * A time-limited QR code session generated by a merchant point-of-sale.
 * The customer scans the QR code, which deep-links into the Centurion wallet.
 * The wallet fetches the session, gets a quote, signs & submits the payment.
 */
export interface QRSessionRecord {
  /** UUID v4, primary key in the qr_sessions table. */
  id: string

  /**
   * Foreign key to PaymentRecord.id once the customer has scanned
   * and initiated a payment.  Undefined while status is PENDING.
   */
  paymentId?: string

  /**
   * Cryptographically random URL-safe token (32 bytes, base64url).
   * Embedded in the QR code URL so scanners cannot enumerate sessions.
   */
  token: string

  /** G… public key of the merchant's Stellar account. */
  merchantAddr: string

  /**
   * Amount the merchant expects to receive in MXN, decimal string.
   * Validated server-side to be a positive number ≤ 999999.9999999.
   */
  amountMxn: string

  /** UTC timestamp after which the session is considered EXPIRED. */
  expiresAt: Date

  /** Current lifecycle state. */
  status: SessionStatus

  /** UTC timestamp when the backend created this record. */
  createdAt: Date
}

// ---------------------------------------------------------------------------
// NFC / SoftPOS types
// ---------------------------------------------------------------------------

/**
 * Payload emitted by the Android Chrome NFC reader (Web NFC API).
 * The POS writes this onto the NFC tag; the wallet reads it.
 */
export interface NFCPayload {
  /** Same as QRSessionRecord.token – reuses the QR session infrastructure. */
  sessionToken: string

  /** Human-readable merchant display name (shown in wallet confirm screen). */
  merchantName: string

  /** Unix epoch seconds – client validates tag is fresh (max 5-min skew). */
  issuedAt: number
}

// ---------------------------------------------------------------------------
// Rate / price types
// ---------------------------------------------------------------------------

/** Live exchange-rate snapshot used for quoting. */
export interface ExchangeRates {
  /** How many MXN equal 1 USD. */
  USD_MXN: string

  /** How many MXN equal 1 GOLD (troy-ounce equivalent token). */
  GOLD_MXN: string

  /** ISO-8601 timestamp of when this snapshot was fetched / cached. */
  updatedAt: string
}

// ---------------------------------------------------------------------------
// Stellar path-find result (internal model, not the raw Horizon response)
// ---------------------------------------------------------------------------

/** Normalised path returned from Horizon strict-receive path-find. */
export interface PathFindResult {
  /** Asset the sender will spend. */
  sourceAsset: AssetCode

  /** Maximum units of sourceAsset to send (includes slippage buffer). */
  sendMax: string

  /** Intermediate hops, in order. */
  path: AssetCode[]

  /** Human-readable exchange rate (destAmount / sendMax, 4 d.p.). */
  rate: string
}

// ---------------------------------------------------------------------------
// Merchant configuration (stored in DB, returned on authenticated endpoints)
// ---------------------------------------------------------------------------

export interface MerchantConfig {
  /** G… public key – also the primary identifier. */
  address: string

  /** Display name shown in QR / NFC payment screens. */
  name: string

  /** ISO-3166-1 alpha-2 country code (e.g. "MX"). */
  country: string

  /** Whether the merchant has completed KYC. */
  verified: boolean

  createdAt: Date
}
